//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TBLCLIENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLCLIENT()
        {
            this.TBLSALES = new HashSet<TBLSALES>();
        }
    
        public int CLIENTNID { get; set; }
        [Required(ErrorMessage ="Please Enter Client Name !")]
        [StringLength(50,ErrorMessage ="You can type up to 50")]
        public string CLIENTNAME { get; set; }
        [Required(ErrorMessage = "Please Enter Client SurName !")]
        [StringLength(50, ErrorMessage = "You can type up to 50")]
        public string CLIENTSURNAME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLSALES> TBLSALES { get; set; }
    }
}
