//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLSALES
    {
        public int SALEID { get; set; }
        public Nullable<int> PRODUCT { get; set; }
        public Nullable<int> CLIENT { get; set; }
        public Nullable<byte> ITEM { get; set; }
        public Nullable<decimal> PRICE { get; set; }
    
        public virtual TBLCLIENT TBLCLIENT { get; set; }
        public virtual TBLPRODUCT TBLPRODUCT { get; set; }
    }
}
